### ISSUE TITLE
ESpHome 2025.2.0

### ISSUE THREAD

**Issue by leovj** [michelsciortino/esphome-aurora-inverter#19]
Unfortunately, with the new version of esphome there are two changes to make:
- Please remove the `platform` key from the [esphome] block and use the correct platform component. This style of configuration has now been removed.
-   The "custom" component has been removed. Consider conversion to an external component.

if for the first change the modification could be this:
`esphome:
  name: xxxx
esp32:
  board: esp32doit-devkit-v1`

I have difficulty fixing "custom" components, i.e. using an external component.
Can anyone help me?

**Comment by bdkacz** [comment]
Author of component should convert it to  external component

**Comment by leovj** [comment]
Yes, I really hope the project can be updated!

**Comment by bdkacz** [comment]
When I find some time I will try to modify it myself, additionally adding support for several inverters :)

**Comment by leovj** [comment]
I have found this "temporary" solution:

https://github.com/robertklep/esphome-custom-component

Good Luke! ;)

**Comment by patrick-mahoney** [comment]
Thank you to you all for this discussion.   Building on leovj's suggestion, I did as suggested but ran into a few minor issues.

I am a bit of a git novice and definitely esphome is totally new to me so maybe there are better ways to do this, but this worked for me.

I had to clone the custom component into ./components - otherwise I got an error.
```
  git clone https://github.com/robertklep/esphome-custom-component.git
  cd esphome-custom-component/
  mv components/ ..
```

And then a few slight modification to config.yaml:
```

external_components:
  - source: "./components"
    components: [ custom, custom_component ]

esphome:
  name: inverter
  includes:
    - ABBAuroraStrings.cpp
    - ABBAuroraStrings.h
    - ABBAuroraEnums.h
    - ABBAurora.cpp
    - ABBAurora.h
    - InverterMonitor.h
  libraries:
    - "Wire"

esp32:
  board: platformio_board_id

wifi:
  ssid: SSID
  password: ""

captive_portal:
logger:
api:
ota:
  platform: esphome

<etc>
```

This built clean for me
